run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 5
