// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	Active    bool         `json:"active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type ApiKeyRole struct {
	ApiKeyID   uuid.UUID `json:"api_key_id"`
	RoleID     uuid.UUID `json:"role_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type AuditLog struct {
	ID           uuid.UUID `json:"id"`
	ApiKeyID     uuid.UUID `json:"api_key_id"`
	Action       string    `json:"action"`
	Resource     string    `json:"resource"`
	StatusCode   int32     `json:"status_code"`
	LatencyMs    int64     `json:"latency_ms"`
	Ip           string    `json:"ip"`
	CreatedAt    time.Time `json:"created_at"`
	RequestBody  string    `json:"request_body"`
	ResponseBody string    `json:"response_body"`
	ToolName     string    `json:"tool_name"`
}

type Permission struct {
	ID       uuid.UUID `json:"id"`
	RoleID   uuid.UUID `json:"role_id"`
	Resource string    `json:"resource"`
	Action   string    `json:"action"`
}

type RateLimit struct {
	ID              uuid.UUID `json:"id"`
	ApiKeyID        uuid.UUID `json:"api_key_id"`
	RequestsPerMin  int32     `json:"requests_per_min"`
	RequestsPerHour int32     `json:"requests_per_hour"`
	RequestsPerDay  int32     `json:"requests_per_day"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}
