// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, key_prefix, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, key_hash, key_prefix, expires_at, active, created_at, updated_at
`

type CreateAPIKeyParams struct {
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, key_prefix, expires_at, active, created_at, updated_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, expires_at, active, created_at, updated_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	Active    bool         `json:"active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, id)
	return err
}
