// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, key_prefix, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, key_hash, key_prefix, expires_at, active, created_at, updated_at
`

type CreateAPIKeyParams struct {
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, key_prefix, expires_at, active, created_at, updated_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRateLimitByKeyID = `-- name: GetRateLimitByKeyID :one
SELECT id, api_key_id, requests_per_min, burst_size
FROM rate_limits
WHERE api_key_id = $1
`

type GetRateLimitByKeyIDRow struct {
	ID             uuid.UUID `json:"id"`
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	RequestsPerMin int32     `json:"requests_per_min"`
	BurstSize      int32     `json:"burst_size"`
}

func (q *Queries) GetRateLimitByKeyID(ctx context.Context, apiKeyID uuid.UUID) (GetRateLimitByKeyIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRateLimitByKeyID, apiKeyID)
	var i GetRateLimitByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RequestsPerMin,
		&i.BurstSize,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (api_key_id, action, resource, status_code, latency_ms, ip, request_body, response_body, tool_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	ApiKeyID     uuid.UUID `json:"api_key_id"`
	Action       string    `json:"action"`
	Resource     string    `json:"resource"`
	StatusCode   int32     `json:"status_code"`
	LatencyMs    int64     `json:"latency_ms"`
	Ip           string    `json:"ip"`
	RequestBody  string    `json:"request_body"`
	ResponseBody string    `json:"response_body"`
	ToolName     string    `json:"tool_name"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ApiKeyID,
		arg.Action,
		arg.Resource,
		arg.StatusCode,
		arg.LatencyMs,
		arg.Ip,
		arg.RequestBody,
		arg.ResponseBody,
		arg.ToolName,
	)
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, expires_at, active, created_at, updated_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	Active    bool         `json:"active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, api_key_id, action, resource, status_code, latency_ms, ip, request_body, response_body, tool_name, created_at
FROM audit_logs
WHERE
    ($1::UUID IS NULL OR api_key_id = $1::UUID) AND
    ($2::TEXT IS NULL OR tool_name = $2::TEXT) AND
    ($3::INT IS NULL OR status_code = $3::INT) AND
    ($4::TIMESTAMPTZ IS NULL OR created_at >= $4::TIMESTAMPTZ) AND
    ($5::TIMESTAMPTZ IS NULL OR created_at <= $5::TIMESTAMPTZ)
ORDER BY created_at DESC
LIMIT $6
`

type ListAuditLogsParams struct {
	ApiKeyID   uuid.NullUUID  `json:"api_key_id"`
	ToolName   sql.NullString `json:"tool_name"`
	StatusCode sql.NullInt32  `json:"status_code"`
	StartTime  sql.NullTime   `json:"start_time"`
	EndTime    sql.NullTime   `json:"end_time"`
	PageLimit  int32          `json:"page_limit"`
}

type ListAuditLogsRow struct {
	ID           uuid.UUID `json:"id"`
	ApiKeyID     uuid.UUID `json:"api_key_id"`
	Action       string    `json:"action"`
	Resource     string    `json:"resource"`
	StatusCode   int32     `json:"status_code"`
	LatencyMs    int64     `json:"latency_ms"`
	Ip           string    `json:"ip"`
	RequestBody  string    `json:"request_body"`
	ResponseBody string    `json:"response_body"`
	ToolName     string    `json:"tool_name"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.ApiKeyID,
		arg.ToolName,
		arg.StatusCode,
		arg.StartTime,
		arg.EndTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Action,
			&i.Resource,
			&i.StatusCode,
			&i.LatencyMs,
			&i.Ip,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ToolName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, id)
	return err
}

const upsertRateLimit = `-- name: UpsertRateLimit :one
INSERT INTO rate_limits (api_key_id, requests_per_min, burst_size)
VALUES ($1, $2, $3)
ON CONFLICT (api_key_id)
DO UPDATE SET requests_per_min = EXCLUDED.requests_per_min, burst_size = EXCLUDED.burst_size
RETURNING id, api_key_id, requests_per_min, burst_size
`

type UpsertRateLimitParams struct {
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	RequestsPerMin int32     `json:"requests_per_min"`
	BurstSize      int32     `json:"burst_size"`
}

type UpsertRateLimitRow struct {
	ID             uuid.UUID `json:"id"`
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	RequestsPerMin int32     `json:"requests_per_min"`
	BurstSize      int32     `json:"burst_size"`
}

func (q *Queries) UpsertRateLimit(ctx context.Context, arg UpsertRateLimitParams) (UpsertRateLimitRow, error) {
	row := q.db.QueryRowContext(ctx, upsertRateLimit, arg.ApiKeyID, arg.RequestsPerMin, arg.BurstSize)
	var i UpsertRateLimitRow
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RequestsPerMin,
		&i.BurstSize,
	)
	return i, err
}
