// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
